### ISSUE TITLE
Feature request: Have two users pick a group of 5 players and see who does better.

### ISSUE THREAD

**Issue by bjmendez** [Manvijay/stats-o-score#109]
Hi All,

I was responsible for alpha testing your project and thought this would be a cool feature to add. As of right now, you can compare two players and see who has done better. I think you could add a lot of depth if you made it so two users could pick 5 players and then see whos team as a whole wins the most statistical categories.

**Comment by sakdec10** [comment]
Hi thanks for testing,
Although I really like the idea the main problem is space management in android app because of limited screen real-estate.

Showing pictures of all 4-5 players could take time to load as well as well will make the app a little congested.
