### ISSUE TITLE
Alpha Testing - Feature Request: Matchup Stats

### ISSUE THREAD

**Issue by yxue5** [Manvijay/stats-o-score#125]
I feel that adding advanced Matchup stats can make this app even better. For example, if a player double taps on a match score, they can see stats related to the matchup history of these teams such as total goals scored, shutouts, and wins/losses between each other.

**Comment by Manvijay** [comment]
Yeah we are planning on adding this feature in the future. We will inform the users whenever we will roll this feature out. Thanks for the suggestion!
