### ISSUE TITLE
[Alpha Testing] Feature Request - Users Gamble With Play Money

### ISSUE THREAD

**Issue by ghost** [Manvijay/stats-o-score#126]
This app would be very cool if there is a feature which users can gamble with play money based on the winning of the team. This allows users to enjoy more than just seeing stats, but also interact with the app in a different level.

**Comment by Manvijay** [comment]
That seems like a good suggestion. We will discuss the possibility of adding this in our next team meeting as we have to consider the ethics protocol as well. Cheers!
