### ISSUE TITLE
[Trivial Bug] If two soccer player some status level number is the same, always the right side player wins.

### ISSUE THREAD

**Issue by ziangzha** [Manvijay/stats-o-score#127]
As the picture showed in the bottom. Petersen and Jason's Penalties are both 72, but Jason wins, Petersen loose.

![548904460](https://user-images.githubusercontent.com/36140953/39019666-ab067c2e-445c-11e8-96a1-befa9dcf3919.jpg)

**Comment by Manvijay** [comment]
Thanks for pointing that out. We will fix that problem in our next release. Cheers!
