### ISSUE TITLE
Modify the search_activity.xml file

### ISSUE THREAD

**Issue by Deepaklather** [Manvijay/stats-o-score#58]
Search_activity.xml file contains two Text fields and one button. Text fields are used for player names and there is a battle button. So I just want to get some modification in the layout like font color, background color of text fields so that the page looks attractive and convert the shape of button from rectangular to circle.

**Comment by kart2k15** [comment]
Where is the file located, in short you want me to add a different XSL stylesheet to this XML file?

**Comment by Deepaklather** [comment]
The file is in res->layout->search_layout.xml folder.
And you do not need to make any extra xml file. You just need to make some changes in same file.

**Comment by kart2k15** [comment]
Is it activity_search.xml ? (instead of search_activity.xml). Besides there is no class today, so you want to meet up then?

**Comment by Deepaklather** [comment]
yes it is activity_search.xml file. Today i am not in campus. So can we meet tomorrow around 1pm?

**Comment by kart2k15** [comment]
Bro, How about 1pm today at Baldy ? @Deepaklather

**Comment by Deepaklather** [comment]
I have classes till 3pm. So can we meet after that?
