### ISSUE TITLE
[Feature request] for saved stats comparison

### ISSUE THREAD

**Issue by lonesai** [Manvijay/stats-o-score#76]
It would be useful if there was a feature where a user could save the stats comparison they searched for so they can access it easier, where as they would have to search for it every time they wanted to view it again.

**Comment by sakdec10** [comment]
Hi, @lonesai  thanks for testing our app and with the valuable feedback.
This is a great idea by you we will surely look into for the beta.
We were looking to merge the search and battle part together to create a seamless view. We might be able to shows past searches or create a side for saved battles from past.
